import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Clock3, Guitar, Music2, Users, Plus, Sparkles, Check } from 'lucide-react';
import { useMinistry } from '../context/MinistryContext';
import { EmptyState, PageHeader } from '../components/ui';

export function dateParts(date: string) {
  const value = new Date(`${date}T12:00:00`);
  return { day: value.toLocaleDateString('pt-BR', { day: '2-digit' }), month: value.toLocaleDateString('pt-BR', { month: 'short' }).replace('.', ''), full: value.toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' }) };
}
export default function HomePage() {
  const { data, profile, canPlan, mode } = useMinistry();
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  const upcoming = [...data.services].filter(s => s.date >= today).sort((a,b) => `${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));
  const next = upcoming[0];
  const mine = next?.assignments.filter(a => a.personId === profile?.personId) || [];
  const nextDate = next ? dateParts(next.date) : null;
  return <><PageHeader eyebrow="SEU MINISTÉRIO, EM HARMONIA" title={`Olá, ${profile?.name.split(' ')[0] || 'equipe'} 👋`} description="Tudo pronto para servir juntos? Veja o que vem por aí." action={canPlan ? <Link className="button button-primary" to="/cultos?novo=1"><Plus size={18} />Novo culto</Link> : undefined} />
  <div className="dashboard-stats"><div className="stat-card"><span className="stat-icon"><CalendarDays /></span><div><strong>{upcoming.length}</strong><span>próximos cultos</span></div></div><div className="stat-card"><span className="stat-icon"><Music2 /></span><div><strong>{data.songs.length}</strong><span>músicas na biblioteca</span></div></div><div className="stat-card"><span className="stat-icon"><Users /></span><div><strong>{data.people.length}</strong><span>pessoas na equipe</span></div></div></div>
  {next ? <><section className="next-service"><div className="next-service-copy"><span className="label-pill"><span className="status-dot" />PRÓXIMO CULTO</span><h2>{next.type}</h2><p className="next-date"><CalendarDays size={18} />{nextDate?.full}<span className="next-divider" /><Clock3 size={18} />{next.time}</p>{mine.length > 0 ? <p className="your-assignment"><Check size={17} />Você está escalado: <strong>{mine.map(a => a.function).join(', ')}</strong></p> : <p className="your-assignment"><Guitar size={17} />Um novo encontro para adorar juntos.</p>}<Link className="button button-light" to={`/cultos/${next.id}`}>Abrir culto<ArrowRight size={18} /></Link></div><div className="hero-art" aria-hidden="true"><div className="hero-disc"><Music2 size={78} strokeWidth={1} /></div><span className="hero-note note-one">♪</span><span className="hero-note note-two">♫</span><span className="hero-line line-one" /><span className="hero-line line-two" /><span className="hero-line line-three" /></div></section>
  <div className="dashboard-columns"><section className="card dashboard-repertoire"><div className="card-heading"><div><p className="eyebrow">PARA O PRÓXIMO CULTO</p><h2>Nosso repertório</h2></div><Link to={`/cultos/${next.id}`} className="text-link">Ver culto<ArrowRight size={15} /></Link></div>{next.repertoire.length ? <ol className="home-song-list">{next.repertoire.map((item,index) => { const song = data.songs.find(s => s.id === item.songId); return <li key={item.id}><Link to={`/musicas/${item.songId}?service=${next.id}&item=${item.id}`}><span className="song-number">{String(index + 1).padStart(2,'0')}</span><span className="song-list-copy"><strong>{song?.title || 'Música indisponível'}</strong><span>{song?.artist}</span></span><span className="key-badge">{item.key}</span><ArrowRight size={16} className="muted" /></Link></li>; })}</ol> : <EmptyState title="O repertório ainda vai chegar" description="As músicas aparecerão aqui quando o líder preparar o culto." />}</section><section className="card dashboard-team"><div className="card-heading"><div><p className="eyebrow">QUEM VAI ESTAR COM VOCÊ</p><h2>Equipe escalada</h2></div><span className="count-badge">{next.assignments.length}</span></div><div className="home-team-list">{next.assignments.map(a => { const person = data.people.find(p => p.id === a.personId); return <div key={a.id} className="home-team-person"><span className={`avatar ${person?.id === profile?.personId ? 'avatar-green' : ''}`}>{person?.name.split(' ').map(n => n[0]).slice(0,2).join('')}</span><div><strong>{person?.name || 'Pessoa indisponível'}{person?.id === profile?.personId && <span className="you-tag">você</span>}</strong><span>{a.function}</span></div></div>; })}{!next.assignments.length && <p className="muted">A equipe ainda não foi definida.</p>}</div><Link className="team-footer" to={`/cultos/${next.id}`}>Ver escala completa<ArrowRight size={16} /></Link></section></div></> : <section className="card"><EmptyState title="Vamos preparar o primeiro culto?" description="Cadastre músicas e pessoas, depois monte a escala e o repertório." action={canPlan && <Link to="/cultos?novo=1" className="button button-primary">Criar culto<Plus size={18} /></Link>} /></section>}
  <section className="upcoming-section"><div className="section-heading"><h2>Próximos encontros</h2><Link className="text-link" to="/cultos">Todos os cultos<ArrowRight size={16} /></Link></div><div className="upcoming-grid">{upcoming.slice(1,4).map(service => { const d = dateParts(service.date); return <Link key={service.id} to={`/cultos/${service.id}`} className="upcoming-card"><span className="date-tile"><strong>{d.day}</strong><span>{d.month}</span></span><div><h3>{service.type}</h3><p><Clock3 size={14} />{service.time}<span>·</span>{service.repertoire.length} músicas</p></div><ArrowRight size={18} /></Link>; })}{upcoming.length < 2 && <p className="muted">Os próximos cultos aparecerão aqui.</p>}</div></section><div className="dashboard-note"><Sparkles size={19} /><p>{mode === 'public' ? 'Acompanhe o ministério. Você pode ajustar o tom das cifras para cantar junto.' : 'Uma chama acesa, muitas vozes para adorar juntos.'}</p></div></>;
}
